stages:
  ingest:
    cmd: python src/ingest.py
    deps:
      - src/ingest.py
      - data/simulation_stream/01_base_data.csv
    outs:
      - data/raw/current_data.csv

  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw/current_data.csv
    outs:
      - data/processed/train.parquet
      - data/processed/val.parquet
      - data/processed/scaler.pkl

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/train.parquet
      - data/processed/scaler.pkl
    params:
      - train.learning_rate
      - train.batch_size
      - train.epochs
      - train.architecture.dropout_rate
      - train.architecture.hidden_1
      - train.architecture.hidden_2