# src/export.py
import mlflow
from mlflow.tracking import MlflowClient
import shutil
import os

mlflow.set_tracking_uri("sqlite:///mlflow.db")
client = MlflowClient()
model_name = "CreditRisk_PyTorch_Model"

print("1. Locating the newest version of the model...")
versions = client.search_model_versions(f"name='{model_name}'")
latest_version = sorted(versions, key=lambda v: int(v.version), reverse=True)[0]
run_id = latest_version.run_id

print(f"Targeting Version {latest_version.version} (Run ID: {run_id})")

print("2. Downloading the PyTorch model...")
mlflow.artifacts.download_artifacts(
    artifact_uri=f"models:/{model_name}/{latest_version.version}",
    dst_path="production_model"
)

print("3. Downloading the scaler...")
try:
    mlflow.artifacts.download_artifacts(
        artifact_uri=f"runs:/{run_id}/model/scaler.pkl",
        dst_path="production_model"
    )
    print("✅ Scaler successfully extracted from MLflow!")
except Exception:
    print("⚠️ Scaler not found in this specific MLflow run.")
    print("🔄 Falling back to local DVC pipeline files...")
    
    # Fallback: Copy the physical file generated by DVC
    local_scaler_path = "data/processed/scaler.pkl"
    if os.path.exists(local_scaler_path):
        shutil.copy(local_scaler_path, "production_model/scaler.pkl")
        print("✅ Local scaler.pkl successfully copied to 'production_model'!")
    else:
        print(f"❌ CRITICAL ERROR: Could not find {local_scaler_path}. Did you run 'python src/preprocess.py'?")